name: Deploy & Restart

on:
  push:
    branches: [ "main", "master" ]

jobs:
  restart-server:
    runs-on: ubuntu-latest
    steps:
      - name: Send Restart Signal
        env:
          PTERODACTYL_HOST: ${{ secrets.PTERODACTYL_HOST }}
          PTERODACTYL_SERVER_ID: ${{ secrets.PTERODACTYL_SERVER_ID }}
          PTERODACTYL_API_KEY: ${{ secrets.PTERODACTYL_API_KEY }}
        run: |
          curl --fail-with-body -X POST \
            "$PTERODACTYL_HOST/api/client/servers/$PTERODACTYL_SERVER_ID/power" \
            -H "Authorization: Bearer $PTERODACTYL_API_KEY" \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.pterodactyl.v1+json" \
            -d '{"signal": "restart"}'
